name: unisal
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - cudatoolkit=9.2
  - pytorch=1.0
  - torchvision
  - opencv=3.4
  - scipy
  - pip:
    - fire==0.2
    - tensorboardX==1.6
